<?php

$base_url = 'https://www.data.gouv.fr/fr/datasets/base-officielle-des-codes-postaux/';

if (preg_match('/([^"]*\.csv)/', curl($base_url), $m)) {
    $url = $m[1];
    $l = explode("\n", curl($url));
    
    array_shift($l);

    $r = array();
    $allTowns = array();
    foreach ($l as $e) {
        if (!$e) continue;
        list($insee,$_, $code, $town) = explode(';', $e);
        if (!isset($r[$code])) $r[$code] = array();
        $r[$code][] = $town;
        $allTowns[] = $town;
    }

    ksort($r);
    $allTowns = array_unique($allTowns);
    sort($allTowns);
    gen(array('frenchPostalCodes' => $r, 'allTowns' => $allTowns));
}

function curl($url) {
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL,$url);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);

    $out = curl_exec($ch);
    curl_close($ch);
    return $out;
}
function gen($l_name) {

  echo "<?php\n\n// Generated by genFrenchPostalCodes\n\n";

  foreach ($l_name as $name => $v) {
      echo 'global $' . $name . '; $' . $name . ' = ';
      var_export($v);
      echo ";\n\n";
  }

  echo "?>\n";
}
